name: Simple-Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update docker-compose with commit SHA and version
        run: |
          COMMIT_SHA=${{ github.sha }}
          VERSION=$(date +'%Y%m%d-%H%M')
          sed -i "s/DD_GIT_COMMIT_SHA=\"\"/DD_GIT_COMMIT_SHA=\"$COMMIT_SHA\"/" docker-compose.yml
          sed -i "s/DD_VERSION=1.0.0/DD_VERSION=$VERSION/" docker-compose.yaml
          cat docker-compose.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update docker-compose.yaml with commit SHA ${{ github.sha }} and version $VERSION"
          git push
